// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeEditor.Infrastructure;

#nullable disable

namespace TreeEditor.Infrastructure.Migrations
{
    [DbContext(typeof(TreeDbContext))]
    [Migration("20260930123511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreeEditor.Core.Domain.TreeNode", entityBuilder =>
                {
                    entityBuilder.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    entityBuilder.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    entityBuilder.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("value");

                    entityBuilder.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    entityBuilder.HasKey("Id")
                        .HasName("tree_nodes_pkey");

                    entityBuilder.HasIndex("ParentId", "Id")
                        .HasDatabaseName("ix_tree_nodes_parent_id_id");

                    entityBuilder.ToTable("tree_nodes", null, tableBuilder =>
                        {
                            tableBuilder.HasCheckConstraint("tree_nodes_check", "parent_id IS DISTINCT FROM id");

                            tableBuilder.HasCheckConstraint("tree_nodes_value_check", "length(btrim(value)) BETWEEN 1 AND 500");

                            tableBuilder.HasCheckConstraint("tree_nodes_version_check", "version > 0");
                        });
                });

            modelBuilder.Entity("TreeEditor.Infrastructure.TreeInitialization", entityBuilder =>
                {
                    entityBuilder.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    entityBuilder.HasKey("Id")
                        .HasName("tree_initialization_pkey");

                    entityBuilder.ToTable("tree_initialization", null, tableBuilder =>
                        {
                            tableBuilder.HasCheckConstraint("tree_initialization_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("TreeEditor.Core.Domain.TreeNode", entityBuilder =>
                {
                    entityBuilder.HasOne("TreeEditor.Core.Domain.TreeNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("tree_nodes_parent_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
